### PR TITLE
Fix typo and change diagram format

### PR DESCRIPTION
**Pull request by ricott1**
Fix typo in Account section: https://github.com/LiskHQ/lisk-docs/issues/860

Change diagram format to svg and remove unif_diagrams nested folder.

### CODE REVIEW

**Comment by ricott1** [comment]
The diagrams size is left to default. However, the transaction schema diagrams would look nicer if rescaled from the original size. AFAIK, there is no easy way to do this with asciidoc (scale, and scaledwidth options did not work). We could still change them all one by one

**Comment by MaximeGagnebin** [comment]
For reference: in the code, the array storing the votes cast by an account is called `sentVotes` (see https://github.com/LiskHQ/lisk-sdk/blob/498013319f16a52d38fe0bfdf4ecced1a1ac62d2/framework/src/modules/dpos/schema.ts#L86). This naming is used here too for consistency.

**Review by AndreasKendziorra — APPROVED** [review]
The change regarding 'votes' -> 'sentVotes' looks good to me. But I did not check the diagram formats.

**Comment by Tschakki** [comment]
@ricott1 please use `docs-sdk` as base branch for your PR, we moved the Lisk protocol content over there

**Pull request closed without merging**
