### PR TITLE
Improve navigation - Closes #1437

### LINKED ISSUE #1437: UI nav improvements
### Description

- Add border to topnav dropdown
image

- Improve styling of current page in nav
image

### PR DESCRIPTION
**Pull request by Tschakki**
Closes #1437

### CODE REVIEW

**Review by chris529 — APPROVED** [review]
LGTM! 👍

**Comment by shuse2** [comment]
I think font and alignment on the selected sidebar is different from the design.
  * the font size and weight should be the same
  * alignment of the letter should not change

the border style / top bar style is different from the design, but is this aligned with @ann-vashchenko ?

**Comment by Tschakki** [comment]
Yes it was one of the requests for this PR to update the borders accordingly, they should be good now.

I applied the other feedback, please check again @shuse2

**Comment by shuse2** [comment]
I think as per design, selected link shouldn't have blue background?

Screenshot 2022-04-11 at 12 09 30

**Comment by Tschakki** [comment]
Yes I think it should, the desired design is also displayed in the issue description #1437

**Comment by shuse2** [comment]
Ah sorry, it is correct it should have background blue.
The  design wise, it should be the whole raw (but i think it would be difficult?). If so, I think it should have some padding on left so the letter is not sticked to the left boarder (maybe discuss with @ann-vashchenko

**Comment by Tschakki** [comment]
Yes, I think it would make it more difficult to have the background color the whole row. Some small padding would be the easier solution. Maybe we can go for the easy solution now, and then request Annas review? If she has any objections, she can include it there.

**Review by shuse2 — APPROVED** [review]

**Comment by ann-vashchenko** [comment]
Hi @Tschakki @shuse2 What do you think if the active item will look like this?
Screenshot 2022-04-11 at 14 47 05

**Pull request merged**
