### PR TITLE
Fix broken links in SDK docs 3.0.2- Closes #639

### LINKED ISSUE #639: Broken links
**Describe the bug**
Some links are broken in the SDK docs (visible in the UI  through their yellow color), e.g. on https://lisk.io/documentation/lisk-sdk/setup.html

### PR DESCRIPTION
**Pull request by chris529**
Closes issue #639

### CODE REVIEW

**Review by Tschakki — CHANGES_REQUESTED** [review]
Please check again, these pages still have some broken links:

https://liskhq.github.io/lisk-docs/lisk-sdk/guides/app-development/interact-with-api.html
https://liskhq.github.io/lisk-docs/lisk-sdk/references/index.html
https://liskhq.github.io/lisk-docs/lisk-sdk/references/lisk-elements/index.html
https://liskhq.github.io/lisk-docs/lisk-sdk/references/lisk-elements/api-client.html
https://liskhq.github.io/lisk-docs/lisk-sdk/references/lisk-elements/client.html
https://liskhq.github.io/lisk-docs/lisk-sdk/references/lisk-elements/validator.html

**Comment by chris529** [comment]
Hey Mona, Well spotted! I think they should all be covered now 👍

**Review by Tschakki — CHANGES_REQUESTED** [review]
Ok cool! I just spotted one other page: https://liskhq.github.io/lisk-docs/lisk-sdk/setup.html

**Review by Tschakki — CHANGES_REQUESTED** [review]
Still one broken link here: https://liskhq.github.io/lisk-docs/lisk-sdk/setup.html

**Comment by chris529** [comment]
Hey Mona! It should now be OK 👍

**Review by Tschakki — APPROVED** [review]
Thank you!

**Pull request merged**
