### PR TITLE
Resize and centre certain images and diagrams in Lisk docs - Closes #1454 

### LINKED ISSUE #1454: Resize certain images/diagrams in Lisk docs
Some of the images/diagrams are too large.
Check and amend the relevant oversized images and diagrams.

### PR DESCRIPTION
**Pull request by chris529**
Closes #1454

### CODE REVIEW

**Review by mitsuaki-u — APPROVED** [review]
🚀

**Review by Tschakki — CHANGES_REQUESTED** [review]
Overall looking good, but this might have slipped through the previous PR:
When looking at the images, some of the text in the images seems to be a little blurry. Please improve the quality of the images, so the text looks sharp and clear.

Example:
image

**Review by Tschakki — CHANGES_REQUESTED** [review]
Hey,
there are still a few remaining issues with the images:
- launch/testnet-delegate-nodes.png: please remove the white background from the green texts
- https://liskhq.github.io/lisk-docs/_images/architecture.png please remove the white white background, the light grey background is already enough
- there are still  some images which are kind of blurry. I checked Lucidchart files, and it looks like you created images of the text in these diagrams. This highly affects quality of the image and the text on it. Please use the Textbox-features of Lucid chart for basically every text that is on the diagram.

**Comment by chris529** [comment]
Hey Mona, No worries, I will check and amend them. 👍

**Review by Tschakki — APPROVED** [review]
Thank you!

**Pull request merged**
