### PR TITLE
Improve video label styling

### LINKED ISSUE #1735: Improve style of video labels
### Description
The label for videos is not rendered nicely, it looks just like normal text and has no good spacing.

It should be rendered in a nice way that distinguishes from normal text, and also has enough space to other content.

### Affected branch / URL
`development`

### Additional resources
See https://liskhq.github.io/lisk-docs/beta/understand-blockchain/interoperability/sidechain-registration-and-recovery.html#sidechain-recovery for example

### PR DESCRIPTION
**Pull request by Tschakki**
Closes #1735, #1781, #1784

### CODE REVIEW

**Review by chris529 — APPROVED** [review]
LGTM! 👍

**Review by TalhaMaliktz — APPROVED** [review]
LGTM 🎉

**Review by TalhaMaliktz — CHANGES_REQUESTED** [review]
- For synchronicity, I suggest we use the same color pattern as it is used in the rest of the documentation for captions.
    - Green-colored captions for dark mode
    - Blue-colored captions for light mode.
- Is there a way to increase the height of the iframe used for the video, it looks cropped out at the moment. The default iframe size is 1280*720.
```
<iframe width="1280" height="720" src="https://www.youtube.com/embed/BTtLbhSgubA" title="Interoperability with Lisk SDK" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

Also, is the font type the same for image and video captions? 🤔

**Comment by Tschakki** [comment]
The style of image and video caption is now better aligned 👍 

Concerning video size, we have to go with a middle-ground, because videos are currently not responsive.
If we make them bigger they look much too big on mobile screens. Also, video size is not really UI related issue, because you can define it with AsciiDoc.

**Review by TalhaMaliktz — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
