### PR TITLE
Fix broken links in Core docs 2.1.6 - Closes #667

### LINKED ISSUE #667: Broken links in Core 2.1.6 docs
**Describe the bug**
Some links are broken in the SDK docs (visible in the UI through their yellow color), e.g. on https://lisk.io/documentation/lisk-core/index.html

### PR DESCRIPTION
**Pull request by chris529**
Closes #667

### CODE REVIEW

**Review by Tschakki — CHANGES_REQUESTED** [review]
Looking, good, but this page still has a broken link: https://liskhq.github.io/lisk-docs/lisk-core/update/application.html

**Comment by chris529** [comment]
Hey Mona, Well spotted.. I think this one slipped through the net. It should be fixed now 👍

**Comment by chris529** [comment]
Hey Mona, well spotted..I think this one slipped through the net, it should be fixed now 👍

**Review by Tschakki — CHANGES_REQUESTED** [review]
Found another one:
https://liskhq.github.io/lisk-docs/lisk-core/setup/commander.html

**Review by Tschakki — CHANGES_REQUESTED** [review]
Please see my comment above.

**Comment by chris529** [comment]
Hey Mona! Ok, can you please check it now, thanks 👍

**Review by Tschakki — APPROVED** [review]
LGTM 👍

**Pull request merged**
