### PR TITLE
Update footer styles - Closes #1356

### LINKED ISSUE #1356: Update footer
## Which content is outdated?
The footer of the docs UI.

## What should be the new content?
image

Epic: #1294

### PR DESCRIPTION
**Pull request by Tschakki**
Closes #1356

### CODE REVIEW

**Comment by shuse2** [comment]
Screenshot 2022-02-07 at 13 20 32
Can we move up the bottom footer to be visible on the first view?

**Comment by Tschakki** [comment]
Done @shuse2 :)

**Comment by shuse2** [comment]
@Tschakki i think the height on the main panel needs to be updated as well?

**Comment by Tschakki** [comment]
@shuse2 i am not sure I understand what you mean, can you explain more please?

**Comment by Tschakki** [comment]
I did some updates now, let me know if it is good now

**Review by shuse2 — APPROVED** [review]

**Review by chris529 — APPROVED** [review]
LGTM!

**Pull request merged**
