### PR TITLE
Add tutorials/hello-world.adoc to /tutorials index

### PR DESCRIPTION
**Pull request by clarkkozak**
On the [tutorials page](https://lisk.io/documentation/lisk-sdk/tutorials/index.html), this adds the [Hello World](https://lisk.io/documentation/lisk-sdk/tutorials/hello-world.html) example to the table; allowing new SDK users to see an easier example.

Add
  - link to hello-world documentation, estimated time required, complexity, and content to the

### CODE REVIEW

**Comment by clarkkozak** [comment]
I would also like this PR to update the side navigation, being right underneath Tutorials:

Screenshot from 2020-05-30 21-53-00

Unfortunately, I'm unsure how to do so.

**Comment by Tschakki** [comment]
Hey @clarkkozak, thanks for the feedback!

We removed the Hello World tutorial from the Tutorials, because we use it as base example in the Guides. So to learn how to set up the Hello World app, you can now start from the Guides overview: https://lisk.io/documentation/lisk-sdk/guides/index.html

**Comment by clarkkozak** [comment]
> Hey @clarkkozak, thanks for the feedback!
> 
> We removed the Hello World tutorial from the Tutorials, because we use it as base example in the Guides. So to learn how to set up the Hello World app, you can now start from the Guides overview: https://lisk.io/documentation/lisk-sdk/guides/index.html

@Tschakki Thanks for getting back to me! Why not both? Only seeing one tutorial in that list made me feel that there wasn't any other, until I saw Hello World. Developers know that's the place to start when wanting to understand a new SDK / API

**Comment by Tschakki** [comment]
There are plans to add more tutorials soon, but I get your point :) We can restore the Hello World tutorial for now, until we have other simple tutorials.

To add the Hello World tutorials back to the navigation, you need to update the `nav.adoc` file :)

**Comment by clarkkozak** [comment]
Hooray! Thank you! I added it! 

I'm unsure how I can check the UI as well. I'm going through these docs to learn about Lisk and I'd love to be a contributor for the documentation as much as I can. I'm unfamiliar with these .adoc files and syntax. Is it a known open source software?

I appreciate your time !

**Review by Tschakki — APPROVED** [review]
LGTM

**Comment by Tschakki** [comment]
Thanks! We use Antora as documentation generator, which uses Asciidoc :) You can find out more by reading their documentation. A complete UI preview is a little complicated, but if you have an editor with an Asciiidoc plugin, it will render most of the stuff nicely in a preview.

**Comment by clarkkozak** [comment]
Word! I got the extension for VSCode! Cheers! :wine_glass:

**Pull request merged**
