### PR TITLE
Update table style - Closes #1363

### LINKED ISSUE #1363: Update style of tables
## Which content is outdated?
Update the style of tables in the documentation

## What should be the new content?
image

Epic: #1294

### PR DESCRIPTION
**Pull request by Tschakki**
Closes #1363

### CODE REVIEW

**Review by shuse2 — CHANGES_REQUESTED** [review]
I think the borders on the image should be hidden / thinner
Screenshot 2022-02-09 at 18 21 54

**Comment by Tschakki** [comment]
Decreased border width of the head bottom. Other borders are already 1px, which is smallest size. The borders should be visible in the table in my opinion.

**Comment by shuse2** [comment]
@Tschakki i think the border between header and content is still thicker than it should.

for the vertical border, i think it's better to ask @ann-vashchenko ? IMO, it usually obvious with space, so not really necessary

**Comment by Tschakki** [comment]
nvm, I did the requested changes 👍

**Review by shuse2 — APPROVED** [review]

**Pull request merged**
