### PR TITLE
Change payload size limit unit from "kB" to "KiB"

### PR DESCRIPTION
**Pull request by AndreasKendziorra**
The payload size limit must be 15 KiB (15 x 1024 bytes) instead 15 kB (15 x 1000 bytes).

### CODE REVIEW

**Review by Tschakki — DISMISSED** [review]

**Review by IkerAlus — DISMISSED** [review]
LGTM

**Review by IkerAlus — DISMISSED** [review]
LGTM

**Review by MaximeGagnebin — DISMISSED** [review]
Looks good.

**Review by MaximeGagnebin — APPROVED** [review]
still looks good :)

**Review by IkerAlus — APPROVED** [review]

**Pull request merged**
